name: Add Cache Control Headers

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install http-server
        run: npm install -g http-server
      - name: Add Cache Control Headers
        run: |
          echo 'exports.handler = (event, context, callback) => {
            const response = {
              statusCode: 200,
              headers: {
                "Cache-Control": "max-age=31536000, public",
              },
              body: JSON.stringify(event),
            };
            callback(null, response);
          };' > index.js
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
